name: Bug report
description: Report a defect in the integration
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail to reproduce the issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Short description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: How can we reproduce it?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant version
      placeholder: e.g. 2026.2.0
    validations:
      required: true
  - type: input
    id: install_type
    attributes:
      label: HA install type
      description: OS / Supervised / Container / Core
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Host platform
      description: OS + BLE details (local adapter or proxy)
      placeholder: e.g. Raspberry Pi OS + USB BLE adapter
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Integration options
      description: has_light, dimmable, direction_supported, poll_interval
      placeholder: has_light=true, dimmable=false, direction_supported=true, poll_interval=15
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste redacted logs
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate
          required: true
        - label: I removed sensitive/private data from logs
          required: true
