name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.7 black==24.8.0
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (format check)
        run: black --check .
